---
apiVersion: v1
kind: Secret
metadata:
  name: hello-spring-cloud-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-local-arun/hello-spring-cloud-gitops